package com.mes.dom.enumerations.application;

public enum ResourceType {
	PERSONNEL_CLASS,
	PERSON,
	EQUIPMENT_CLASS,
	EQUIPMENT,
	PHYSICAL_ASSET_CLASS,
	PHYSICAL_ASSET,
	MATERIAL_CLASS,
	MATERIAL_DEFINITION,
	MATERIAL_LOT,
	MATERIAL_SUBLOT,
	WORK_MASTER,
	PROCESS_SEGMENT,
}
